# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Color mapping utilities for memory2 visualization."""

from __future__ import annotations

from collections.abc import Iterable, Iterator
import colorsys
from dataclasses import dataclass
import functools


@dataclass
class Color:
    """Deferred color resolved at render time from a value range.

    Elements with the same ``group`` share an auto-computed min/max range.
    Can be used as a factory: ``speed = Color("speed", cmap="turbo"); speed(2.5)``.
    """

    group: str
    value: float | None = None
    cmap: str = "turbo"

    def __call__(self, value: float) -> Color:
        return Color(group=self.group, value=value, cmap=self.cmap)


@functools.lru_cache(maxsize=16)
def _cmap(name: str):  # type: ignore[no-untyped-def]
    import matplotlib.pyplot as plt

    return plt.get_cmap(name)


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert a hex color string like '#1abc9c' to an (R, G, B) tuple."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    return (int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16))


def color(value: float, lo: float = 0.0, hi: float = 1.0, cmap: str = "turbo") -> str:
    """Map a value in [lo, hi] to a hex color string via a matplotlib colormap."""
    t = max(0.0, min(1.0, (value - lo) / (hi - lo))) if hi != lo else 0.5
    r, g, b, _ = _cmap(cmap)(t)
    return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"


# ---------------------------------------------------------------------------
# Named palette: 12 visually-distinct colors that share visual weight.
#
# Indices 0..5 are hand-curated flat-UI colors that match the defaults in
# vis/space/elements.py so a Plot embedded next to a Space drawing reads as
# the same family. Indices 6..11 are generated by gap-subdivision in HSL
# space (preserving the curated set's average L≈0.51 / S≈0.72) so they fill
# the largest hue gaps between the curated colors. Together they form 12
# maximally-distinct hues. Beyond 12, `palette_iter` continues with a
# golden-angle hue walk that uses the same average L/S.
# ---------------------------------------------------------------------------

blue = "#3498db"
red = "#e74c3c"
yellow = "#f1c40f"
teal = "#1abc9c"
purple = "#9b59b6"
orange = "#e67e22"
green = "#4cdc29"
magenta = "#dc2994"
indigo = "#3329dc"
cyan = "#29c9dc"
vermilion = "#dc5b29"
amber = "#dc9a29"

PALETTE: list[str] = [
    blue,
    red,
    yellow,
    teal,
    purple,
    orange,
    green,
    magenta,
    indigo,
    cyan,
    vermilion,
    amber,
]


def _hex_to_hls(hex_color: str) -> tuple[float, float, float]:
    r, g, b = hex_to_rgb(hex_color)
    return colorsys.rgb_to_hls(r / 255, g / 255, b / 255)


def _hls_to_hex(h: float, l: float, s: float) -> str:
    r, g, b = colorsys.hls_to_rgb(h % 1.0, l, s)
    return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"


def palette_iter(
    palette: list[str] = PALETTE,
    exclude: Iterable[str] | None = None,
) -> Iterator[str]:
    """Yield colors forever for auto-assigning Series/Markers.

    Yields ``palette`` in order, then continues indefinitely via a
    golden-angle (137.5°) hue walk anchored at the average L/S of
    ``palette`` so generated colors share visual weight with the named
    ones.

    ``exclude`` is a set of hex strings (e.g. colors the user has already
    pinned to specific series) to skip — case-insensitive.
    """
    excluded = {c.lower() for c in (exclude or ())}

    for c in palette:
        if c.lower() not in excluded:
            yield c

    if not palette:
        return

    hls = [_hex_to_hls(c) for c in palette]
    avg_l = sum(p[1] for p in hls) / len(hls)
    avg_s = sum(p[2] for p in hls) / len(hls)

    # Anchor the walk on the last palette color's hue so the first
    # generated color is offset 137.5° from the end of the named set.
    last_hue = _hex_to_hls(palette[-1])[0]
    golden = 137.5 / 360.0
    while True:
        last_hue = (last_hue + golden) % 1.0
        c = _hls_to_hex(last_hue, avg_l, avg_s)
        if c.lower() not in excluded:
            yield c
